import type { NextPage, GetStaticProps } from 'next'
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import coffeeStoresData from '../data/coffee-store.json'
import Banner from '../components/banner'
import Card from '../components/card'
import styles from '../styles/Home.module.css'

interface Props {
  coffeeStoresData:[{
    id:number;
    imgUrl:string;
    name:string;
    address:string;
    neighbourhood:string;
    websiteUrl:string;
  }]
  
}

export const getStaticProps:GetStaticProps = async () => {
  return {
    props:{
      coffeeStoresData
    }
  }
}

const Home: NextPage<Props> = (props) => {
  const handelOnButton = () => {
    console.log('You clicked the button')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          buttonHandler={handelOnButton} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt="hero image" width={700} height={400} />
        </div>
        {props.coffeeStoresData.length > 0 ? (<>
        <h2 className={styles.heading2}>Torronto Coffee Stores</h2>
               <div className={styles.cardLayout}>
               {props.coffeeStoresData.map(coffeeStore => {
                 return (
                   <Card
                   key={coffeeStore.id}
                   name={coffeeStore.name}
                   href={`/coffee-store/${coffeeStore.id}`}
                   imgURL={coffeeStore.imgUrl} />
                 )
               })}         
             </div>
        </>) : ""   
     }
 
      </main>
    </div>
  )
}

export default Home
